workspace:
  
  base: /go
  path: src/github.com/glynternet/mon


pipeline:

  release:
    image: goreleaser/goreleaser:v0.86
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    commands:
      - git fetch origin +refs/tags/${DRONE_TAG}:refs/tags/${DRONE_TAG}
      - goreleaser release --rm-dist
    when:
      event: tag
