workspace:
  
  base: /go
  path: src/github.com/glynternet/mon


pipeline:

  release:
    image: goreleaser/goreleaser:v0.86
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    commands:
      - printenv
      - echo git fetch origin ${DRONE_COMMIT_REF}
      - echo git fetch origin ${DRONE_REMOTE_URL}
      - echo git fetch origin ${DRONE_COMMIT_LINK}
      - goreleaser release --rm-dist
    when:
      event: tag
