workspace:
  
  base: /go
  path: src/github.com/glynternet/mon


pipeline:

  release:
    image: goreleaser/goreleaser:v0.86
    secrets: [ github_token ]
    commands:
      - git fetch --no-tags origin +refs/tags/${DRONE_TAG}:refs/tags/${DRONE_TAG}
      - goreleaser release --rm-dist
    when:
      event: tag
