workspace:
  
  base: /go
  path: src/github.com/glynternet/mon


pipeline:

  release:
    image: goreleaser/goreleaser:v0.86
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    commands:
      - pwd
      - ls -la
      - git status
      - git tag --list
      - goreleaser release --rm-dist
    when:
      event: tag
