workspace:
  
  base: /go
  path: src/github.com/glynternet/mon


pipeline:

  run-unit-tests:
    image: golang
    commands:
      - go test -v -race ./...
  
  build-monserve-binary:
    image: golang
    commands:
      - make monserve-binary
  
  build-monserve-image:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build --tag monserve:ci-functional-tests-${DRONE_COMMIT_SHA} .
  
  build-client-functional-tests-binary:
    image: golang
    commands:
      - cd test/functional
      - make build-tests
  
  run-functional-tests:
    image: docker/compose:1.21.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_IMAGE=monserve:ci-functional-tests-${DRONE_COMMIT_SHA}
    commands:
      - cd test/functional
      - docker-compose --project-name monserve-client-functional-test down
      - docker-compose --project-name monserve-client-functional-test up --build --abort-on-container-exit --force-recreate
      - docker-compose --project-name monserve-client-functional-test down
