builds:
- binary: monauth
  ldflags:
    - -w -X main.version={{.Version}}
  main: ./cmd/monauth
  env:
  - CGO_ENABLED=0
  goarch:
    - amd64
- binary: moncli
  ldflags:
     - -w -X github.com/glynternet/mon/cmd/moncli/cmd.version={{.Version}}
  main: ./cmd/moncli
  env:
  - CGO_ENABLED=0
  goarch:
    - amd64
- binary: monserve
  ldflags:
     - -w -X main.version={{.Version}}
  main: ./cmd/monserve
  env:
  - CGO_ENABLED=0
  goarch:
    - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{ .Version }}-{{ .Commit }}"
changelog:
  sort: asc

dockers:
- binary: monauth
  dockerfile: bin/Dockerfile.monauth
  image_templates:
  - 'glynhanmer/{{.Binary}}:{{ .Version }}'
- binary: moncli
  dockerfile: bin/Dockerfile.moncli
  image_templates:
  - 'glynhanmer/{{.Binary}}:{{ .Version }}'
- binary: monserve
  dockerfile: bin/Dockerfile.monserve
  image_templates:
  - 'glynhanmer/{{.Binary}}:{{ .Version }}'
