builds:
- binary: moncli
  ldflags:
     - -w -X github.com/glynternet/mon/cmd/moncli/cmd.version={{.Version}}
  main: ./cmd/moncli
  env:
  - CGO_ENABLED=0
  goarch:
    - amd64
- binary: monserve
  ldflags:
     - -w -X main.version={{.Version}}
  main: ./cmd/monserve
  env:
  - CGO_ENABLED=0
  goarch:
    - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{ .Tag }}-{{ .Commit }}"
changelog:
  sort: asc

dockers:
  - binary: moncli
    image_templates:
      - "myuser/{{.Binary}}"
  - binary: monserve
    image_templates:
      - "myuser/{{.Binary}}"